### ISSUE TITLE
How would it work when using Socialite?

### ISSUE THREAD

**Issue by aligajani** [Zemke/starter-laravel-angular#13]
Hey, excellent project. How would this work when I am using OAuth 2 like Facebook with Socialite?

**Comment by Zemke** [comment]
Hey, thank you for your words and thanks for trying out Zemke/starter-laravel-angular. Since this is an AngularJS application, AngularJS takes care of authentication. Laravel is only the endpoint. So you would probably use an AngularJS social login solution (there are many) rather than Laravel’s Socialite.

**Comment by aligajani** [comment]
I think I can just use Socialite? What's stopping me from doing that
effectively.

**Comment by Zemke** [comment]
You can also use Socialite, nothing does effectively make it impossible. There is a login method in the `UserController` one the Laravel side and there is a `UserService` on the Angular side mainly responsible for auth. Also check the Laravel router in correspondence. In combination with the Laravel docs on Socialite you can create a nice auth system with Socialite, too.
Maybe once I will also build it into the project. If you do it, I would be happy about a pull request.

**Comment by aligajani** [comment]
Neat :) I'll send a pull when I'm done
