### ISSUE TITLE
Internal Serval Error

### ISSUE THREAD

**Issue by bwoodlt** [Zemke/starter-laravel-angular#16]
Hi,

Good start point I must say. Have just installed and 'served' the app. When I tried to create a 'todo' list I'm getting this: 'Failed to load resource: the server responded with a status of 500 (Internal Server Error)'.

Could you please advise how to fix this?

Many thanks!

**Comment by Zemke** [comment]
Hey @bwoodlt,

thank you for your words. I'm late, sorry for that, I was busy with other hacks but here's your solution. :)

That's probably due to missing or flawed database setup. I've updated the readme to include instructions on how to set up your database for the application.

Run these commands to create the tables within the database you have already created.

```
php artisan migrate:install
```

```
php artisan migrate:refresh
```

**Comment by bwoodlt** [comment]
@Zemke Brilliant, thanks!
