### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by amilgaul** [Zemke/starter-laravel-angular#24]
I've followed all the instruction regarding with the installation and all of them are successfully done but when im trying to access in http://localhost:8080, unable to connect. What did i miss? Anyone please help. Im using xampp as my local server.

**Comment by Zemke** [comment]
If you're using XAMPP as your local server, you haven't followed all instructions.

The instructions suggest using the PHP built-in server rather than one provide by XAMPP. Nonetheless you can of course use XAMPP, too. But then it's likely that your server is running under http://localhost, rather than http://localhost:8080. At least that's the default for XAMPP.

If that doesn't work for you comment here again, I'm glad to help.
