### ISSUE TITLE
Upgrade Angular to 2.0

### ISSUE THREAD

**Issue by ghost** [Zemke/starter-laravel-angular#36]
Can you explain where i can read article for upgrade Angular in your project?

**Comment by Zemke** [comment]
There are migration guides to be found in the AngularJS docs.

Mostly it’s just “replacing” the `angular.js` file, but often times you also need to update some parts in your codebase.
For Angular 2 it’s more complex, since it’s  major update.

In all cases it’s a general work, nothing specifically related to this project.

**Comment by ghost** [comment]
thx
