### ISSUE TITLE
Page refresh logs me out

### ISSUE THREAD

**Issue by eablokker** [Zemke/starter-laravel-angular#5]
When I refresh the page, it thinks I'm logged out and I have to log back in again.

Do you plan on keeping this project updated? I want to use it for my angular application. This is the only Laravel 5 Angular starter app I could find. I will be making changes on top of it to build my app. Is there a sane way to merge your updates with mine?

**Comment by eablokker** [comment]
Nevermind, fixed it. I had to add this to my Apache .htaccess file as per the [JWT Auth docs](https://github.com/tymondesigns/jwt-auth/wiki/Authentication)

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**Comment by Zemke** [comment]
Hey eablokker,

thank you for the inquiry.

I’m definitely planning on keeping this repo up to date. Of course I’d gladly accept help in the process. You can also profit from the changes although you’ve forked the project at an earlier stage.

Add this repo as a remote.

```
git remote add starter-laravel-angular git@github.com:Zemke/starter-laravel-angular.git
```

Whenever you wish to merge changes from this repo into yours:

```
git pull starter-laravel-angular master
```

A convenient way would be to have an extra branch where you take that process in order to avoid any hassle on the master branch.

If you have any further requests feel free to open another issue. 😊
